// Auto-generated by dsp/export_coefficients.py - do not edit by hand.
// Regenerate with:  python dsp/export_coefficients.py
//
// Acquisition scaling, generated from sim/afe_model.py - the same model the DSP is
// validated through. Do not hand-edit: the device's millivolt and the pipeline's
// millivolt must be the same millivolt.
#pragma once

#include <stdint.h>

#define VS_ADC_BITS          12
#define VS_ADC_FULL_SCALE    4095
#define VS_AFE_GAIN          330
#define VS_SUPPLY_MV         3300

// Code that corresponds to 0 mV at the electrodes (the mid-supply reference).
#define VS_ADC_ZERO_CODE     2048

// Nanovolts at the electrodes per ADC count: (Vfs / 2^bits) / gain.
// counts -> nV is one multiply; nV -> mV is a divide by 1e6 at format time.
#define VS_NV_PER_COUNT      2441

// Within this many codes of a rail, the amplifier has clipped. A detached electrode
// rails the AD8232 output, so this is a signal-side cross-check on the LO pins.
#define VS_RAIL_MARGIN       82

// Input range before the amplifier saturates, in microvolts (D-26: sized from the
// +/-5 mV that IEC 60601-2-27 expects an ECG monitor to accept).
#define VS_INPUT_RANGE_UV    5000
